"""
Django settings for WINT project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import pickle

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--iee&o&kly=tf-=xg6!o@+5*+f58yqzq-p2h0qg+r+h6k$v0bv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mst',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WINT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WINT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

#STATIC_URL = 'kr_stock/static/' #/read/static/
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, 'mst/static/'),
    #os.path.join(BASE_DIR, 'mst/static/'),
    #os.path.join(BASE_DIR, 'mst/static/SUM/'),
    #r'C:\Users\Jinu\PycharmProjects\WEB\WINT\mst\static\SUM',
    #r'C:\Users\Jinu\PycharmProjects\WEB\WINT\mst\static',

    # r'C:\Users\Jinu\PycharmProjects\CYB\JAMU\save\DAILY_300',
    # r'C:\Users\Jinu\PycharmProjects\CYB\JAMU\save\SUM',
    r'C:\Users\Jinu\PycharmProjects\CYB\JAMU\save',
    r'C:\REPORT\rep_raw'
]

#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


with open(r"C:\Users\Jinu\PycharmProjects\WEB\WINT\url_now.pickle", 'rb') as f:
    to_url = pickle.load(f).replace('https://','')



ALLOWED_HOSTS=["d904-121-166-86-162.jp.ngrok.io",
               "cb91-121-166-86-162.jp.ngrok.io",
               "597e-121-166-86-162.jp.ngrok.io",
               "127.0.0.1","http://127.0.0.1:8000/",str(to_url)
               ] #, "localhost", "127.0.0.1"


#<img src="static\SUM\0347_덴티움__3000_4500.png" alt="덴티움" width="80%">

#<img src="static\SUM\0347_덴티움__3000_4500.png" alt="덴티움" width="80%">  #된거